<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>async function</title>
</head>

<body>
	<h1 style="color: blue;">Async keyword</h1>
	<h2>async의 정의</h2>
	<p>
	<h3>async:</h3> 함수를 비동기 함수로 선언하는 키워드
	함수명 앞에 async을 입력해 함수를 비동기 함수로 선언하면
	함수를 자동으로 promise로 변환함</p>
	<pre><code>sing()
		.then((data) => {
		console.log("promise fulfilled with :", data)
		})
		.catch(err => {
		console.log("OH NO, Promise rejected!")
		console.log(err)
		})
		</code></pre>
	<p>
	<h3>결과:</h3>
	<pre>
	OH NO, Promise rejected!
	OH NO, PROBLEM!
	에러가 발생했기 때문에 catch 함수를 콜백한 것을 확인 할 수 있음.
	</pre>
	</p>
	<script src="app.js"></script>
</body>

</html>